In [1]:
%run hello.py

Hello Machine Learning !


In [2]:
hello("imooc")

Hello imooc !


In [3]:
%timeit L = [ i**2 for i in range(1000)]

265 µs ± 5.18 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
%%timeit 
L = []
for n in range(1000):
    L.append(n**2)

276 µs ± 5.34 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
%time L = [ i**2 for i in range(1000)]

CPU times: user 591 µs, sys: 0 ns, total: 591 µs
Wall time: 598 µs


In [6]:
 %lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

In [10]:
import numpy
numpy.__version__

'1.20.1'

In [11]:
L = [i for i in range(10)]

In [12]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
L[5] = 'machine learning'

In [14]:
list
L

[0, 1, 2, 3, 4, 'machine learning', 6, 7, 8, 9]

In [15]:
import array
arr = array.array('i',[i for i in range(10)])

In [16]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
 arr[5] = 'machine learning'

TypeError: an integer is required (got type str)

In [18]:
import numpy as np
nparr = np.array([i for i in range(10)])

In [19]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
nparr[5]

5

In [21]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [22]:
nparr[5] = "machine learning"

ValueError: invalid literal for int() with base 10: 'machine learning'

In [23]:
nparr.dtype

dtype('int64')

In [24]:
nparr[3] = 3.14 

In [25]:
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [26]:
nparr.dtype

dtype('int64')

In [27]:
nparr2 = np.array([1,2,3.0])

In [28]:
nparr2

array([1., 2., 3.])

In [29]:
nparr2.dtype

dtype('float64')

In [30]:
 np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros(10).dtype

dtype('float64')

In [2]:
import numpy as np
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.full((3,5),666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [8]:
np.full(shape=(3,5),fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

# arange

In [10]:
[i for i in range(0,20,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [11]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

两者功能相同，区别在于步长：python中不可以是小数，np中可以是小数

In [12]:
[i for i in range(0,20,0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [13]:
np.arange(0,20,0.2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8])

# linspace

In [15]:
# 功能同arange，但是10是指取10个值，同时包括起始点
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [16]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

# random

In [19]:
np.random.randint(0,10)

9

In [20]:
np.random.randint(4,10,size=(3,5))

array([[9, 4, 7, 6, 6],
       [5, 6, 7, 8, 9],
       [8, 7, 7, 9, 6]])

In [21]:
np.random.randint(4,10,size=(3,5))

array([[4, 4, 5, 4, 4],
       [7, 6, 6, 7, 9],
       [7, 8, 7, 6, 7]])

In [22]:
# 设置相同的随机种子可以获得相同的随机数
np.random.seed(666)

In [23]:
np.random.randint(4,10,size=(3,5))

array([[8, 6, 9, 5, 8],
       [9, 7, 7, 8, 8],
       [5, 4, 4, 9, 6]])

In [24]:
np.random.seed(666)

In [25]:
np.random.randint(4,10,size=(3,5))

array([[8, 6, 9, 5, 8],
       [9, 7, 7, 8, 8],
       [5, 4, 4, 9, 6]])

In [27]:
# random取浮点数
np.random.random()

0.31644109109959084

In [28]:
np.random.random((3,5))

array([[0.15551206, 0.73460987, 0.73159555, 0.8578588 , 0.76741234],
       [0.95323137, 0.29097383, 0.84778197, 0.3497619 , 0.92389692],
       [0.29489453, 0.52438061, 0.94253896, 0.07473949, 0.27646251]])

In [33]:
# 生成符合正态分布的浮点数，均值为0，方差为1
np.random.normal()

0.7760516793129695

In [34]:
# 指定均值和方差
np.random.normal(10,100)

128.06359754812632

In [35]:
np.random.normal(0,1,(3,5))

array([[ 0.06102404,  1.07856138, -0.79783572,  1.1701326 ,  0.1121217 ],
       [ 0.03185388, -0.19206285,  0.78611284, -1.69046314, -0.98873907],
       [ 0.31398563,  0.39638567,  0.57656584, -0.07019407,  0.91250436]])

In [36]:
np.random.normal?

In [37]:
np.random?

# Numpy.array的基本属性

In [1]:
import numpy as np

In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
X = np.arange(15).reshape(3,5)

In [5]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

基本属性

In [6]:
x.ndim

1

In [7]:
X.ndim

2

In [8]:
x.shape

(10,)

In [9]:
X.shape

(3, 5)

In [10]:
x.size

10

In [11]:
X.size

15

numpy.array的数据访问

In [12]:
x[0]

0

In [13]:
x[-1]

9

In [14]:
# numpy中不建议使用这种形式访问多维数组
X[0][0]

0

In [15]:
# 建议使用
X[2,2]

12

In [16]:
x[:5]

array([0, 1, 2, 3, 4])

In [17]:
x[5:]

array([5, 6, 7, 8, 9])

In [18]:
x[::2]

array([0, 2, 4, 6, 8])

In [19]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [20]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [21]:
# 不推荐使用两个中括号来取值的原因：
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [24]:
# numpy.array与list的不同之处:切片索引更改值后原array也会改变，而list不随之改变
sub_X = X[:2,:3]

In [25]:
sub_X[0,0] = 100

In [26]:
sub_X

array([[100,   1,   2],
       [  5,   6,   7]])

In [27]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [28]:
y = [i for i in range(10)]

In [29]:
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [30]:
y_sub = y[:3]

In [31]:
y_sub

[0, 1, 2]

In [32]:
y_sub[1] = 100

In [33]:
y_sub

[0, 100, 2]

In [34]:
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [35]:
# numpy.array如果不想覆盖原值，可以用拷贝copy的方式
subX = X[:2,:3].copy()
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [37]:
subX[1,1] = 100
subX

array([[100,   1,   2],
       [  5, 100,   7]])

In [38]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

Reshape

In [39]:
x.shape

(10,)

In [40]:
x.ndim

1

In [41]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
# 不改变原值
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# 要改变原值可以重新赋值
A = x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
# 二维矩阵
B = x.reshape(1,10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [47]:
B.shape

(1, 10)

In [48]:
x.shape

(10,)

In [49]:
x.reshape(10,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [50]:
x.reshape(-1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

合并操作

In [51]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [52]:
x

array([1, 2, 3])

In [53]:
y

array([3, 2, 1])

In [55]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [56]:
z = np.array([666,666,666])

In [57]:
np.concatenate([x,y,z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [58]:
A = np.array([[1,2,3],
            [4,5,6]])

In [59]:
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [60]:
np.concatenate([A,A],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [62]:
z.shape

(3,)

In [61]:
z.reshape(1,-1)

array([[666, 666, 666]])

In [64]:
np.concatenate([A,z.reshape(1,-1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [66]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
# 需要将z转化矩阵维度才能拼接
A2 = np.concatenate([A,z.reshape(1,-1)])

In [68]:
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [69]:
# 可以智能拼接，不管维度
np.vstack([A,z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [70]:
B = np.full((2,2),100)

In [71]:
B

array([[100, 100],
       [100, 100]])

In [72]:
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

分割操作

In [73]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
x1,x2,x3 = np.split(x,[3,7])

In [76]:
x1

array([0, 1, 2])

In [77]:
A = np.arange(16).reshape((4,4)) 

In [78]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [79]:
A1,A2 = np.split(A,[2])

In [80]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [81]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
A1,A2 = np.split(A,[2],axis=1)

In [83]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [84]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [85]:
upper,lower = np.vsplit(A,[2])

In [86]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [87]:
left,right = np.hsplit(A,[2])

In [88]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

# numpy.array中的运算

In [89]:
L = [i for i in range(10)]

In [90]:
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [91]:
A = []
for e in L:
    A.append(2*e)

In [92]:
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

# Universal Functions

In [94]:
X = np.arange(1,16).reshape((3,5))

In [96]:
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [97]:
X +1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [98]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [99]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [100]:
# 整数除法
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [101]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]], dtype=int32)

In [102]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [103]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [104]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [105]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [106]:
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [108]:
np.power(3,X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [109]:
# 默认e为底
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [110]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

# 矩阵运算

In [112]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [113]:
B = np.full((2,2),10)
B

array([[10, 10],
       [10, 10]])

In [114]:
A + B

array([[10, 11],
       [12, 13]])

In [115]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [116]:
# 对应项运算
A * B

array([[ 0, 10],
       [20, 30]])

In [117]:
# 矩阵运算
A.dot(B)

array([[10, 10],
       [50, 50]])

In [118]:
A

array([[0, 1],
       [2, 3]])

In [119]:
A.T

array([[0, 2],
       [1, 3]])

向量和矩阵的运算

In [120]:
v = np.array([1,2])

In [121]:
v

array([1, 2])

In [122]:
A

array([[0, 1],
       [2, 3]])

In [124]:
np.vstack([v] * A.shape[0]) + A

array([[1, 3],
       [3, 5]])

In [125]:
v.dot(A)

array([4, 7])

In [126]:
# 可以根据A的行列值匹配v作为行向量还是列向量
A.dot(v)

array([2, 8])

矩阵的逆

In [127]:
A

array([[0, 1],
       [2, 3]])

In [128]:
invA = np.linalg.inv(A)

In [129]:
# 矩阵与逆矩阵相乘结果为单位矩阵，但要求矩阵必须为方阵
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [130]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [132]:
X = np.arange(16).reshape((2,8))

In [133]:
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [134]:
# 非方针无法求逆矩阵
np.linalg.inv(X)

LinAlgError: Last 2 dimensions of the array must be square

In [137]:
# 我们可以求伪逆矩阵
pinvX = np.linalg.pinv(X)
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -5.20417043e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [139]:
# 近似为单位矩阵
X.dot(pinvX)

array([[ 1.00000000e+00, -2.49800181e-16],
       [ 6.66133815e-16,  1.00000000e+00]])

# 聚合操作

In [140]:
import numpy as np
L = np.random.random(100)

In [141]:
L

array([0.6968953 , 0.13016313, 0.31327886, 0.01557695, 0.35100838,
       0.73453006, 0.60450513, 0.26749738, 0.66990288, 0.84308313,
       0.2370584 , 0.65059354, 0.62677525, 0.93364596, 0.49099516,
       0.4535212 , 0.3284975 , 0.17986615, 0.74630314, 0.40431831,
       0.65435645, 0.01516975, 0.7415543 , 0.11677417, 0.50964227,
       0.30180786, 0.15490775, 0.25529255, 0.58550694, 0.35995884,
       0.88564082, 0.24072599, 0.43070958, 0.38774293, 0.91810567,
       0.7809219 , 0.79835369, 0.61685855, 0.90811738, 0.77839983,
       0.06888269, 0.0294373 , 0.4069748 , 0.81575012, 0.62280432,
       0.26162294, 0.71567142, 0.10025938, 0.89312386, 0.1694244 ,
       0.03551473, 0.62433552, 0.8444419 , 0.49684269, 0.44736012,
       0.82418747, 0.94846941, 0.0966864 , 0.34582665, 0.29830116,
       0.45468624, 0.81310779, 0.04695207, 0.3367027 , 0.78258169,
       0.64649664, 0.39453816, 0.84194896, 0.87977471, 0.98636941,
       0.02603916, 0.4362094 , 0.27407522, 0.06378524, 0.56030

In [142]:
sum(L)

49.74416310579135

In [143]:
np.sum(L)

49.74416310579135

索引

In [144]:
x = np.random.normal(0,1,size=1000000)

In [145]:
np.mean(x)

-0.0004854751764893467

In [146]:
np.std(x)

0.9999161708303431

In [147]:
np.min(x)

-4.7839424333703136

In [148]:
# 最小值的索引
np.argmin(x)

868197

In [149]:
np.argmax(x)

145038

排序和使用索引

In [153]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [155]:
np.random.shuffle(x)
x

array([ 7,  8,  2,  4,  5, 13, 10,  1,  6,  9, 12,  0, 14,  3, 11, 15])

In [156]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [157]:
x

array([ 7,  8,  2,  4,  5, 13, 10,  1,  6,  9, 12,  0, 14,  3, 11, 15])

In [161]:
x.sort()

In [162]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

# Fancy index

In [164]:
import numpy as np

X = np.arange(16)
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [165]:
ind = [3,5,8]
X[ind]

array([3, 5, 8])

In [166]:
ind = np.array([[0,2],
               [1,3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [167]:
X = X.reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [168]:
row = np.array([0,1,2])
col = np.array([1,2,3])
X[row,col]

array([ 1,  6, 11])

In [169]:
col = [True,False,True,True]

In [170]:
X[1:3,col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

# numpy.array的比较

In [171]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [172]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])